export const XS_MIN = '0px'
export const XS_MAX = '576px'
export const SM_MIN = `${parseInt(XS_MAX) + 1}px`
export const SM_MAX = '768px'
export const MD_MIN = `${parseInt(SM_MAX) + 1}px`
export const MD_MAX = '992px'
export const LG_MIN = `${parseInt(MD_MAX) + 1}px`
export const LG_MAX = '1200px'
export const XL_MIN = `${parseInt(LG_MAX) + 1}px`
export const XL_MAX = '1400px'
export const XXL_MIN = `${parseInt(XL_MAX) + 1}px`
