export const MAX_WIDTH = '730px'
export const MAX_HEIGHT = '720px'
export const CONTAINER_WIDTH = '410px'
export const BASE_SIZE = '1rem'
export const XS_SIZE = `${parseInt(BASE_SIZE) * 1.2}rem`
export const SM_SIZE = `${parseInt(BASE_SIZE) * 1.3}rem`
export const MD_SIZE = `${parseInt(BASE_SIZE) * 1.4}rem`
export const LG_SIZE = `${parseInt(BASE_SIZE) * 2.4}rem`
export const XL_SIZE = `${parseInt(BASE_SIZE) * 3.2}rem`
export const XXL_SIZE = `${parseInt(BASE_SIZE) * 4.8}rem`
