const FOCUSED_BUTTON = 'FOCUSED_BUTTON'
const HIDE_BUTTON = 'HIDE_BUTTON'
const SHOW_BUTTON = 'SHOW_BUTTON'
const HIDE_EVERY_BUTTON = 'HIDE_EVERY_BUTTON,'
const SHOW_EVERY_BUTTON = 'SHOW_EVERY_BUTTON,'

export {
	FOCUSED_BUTTON,
	HIDE_BUTTON,
	SHOW_BUTTON,
	HIDE_EVERY_BUTTON,
	SHOW_EVERY_BUTTON
}
