const FOCUSED_BUTTON = 'FOCUSED_BUTTON'
const UNFOCUSED_BUTTON = 'UNFOCUSED_BUTTON'
const HIDE_BUTTON = 'HIDE_BUTTON'
const SHOW_BUTTON = 'SHOW_BUTTON'
const DISABLE_BUTTON = 'DISABLE_BUTTON'
const UNABLE_BUTTON = 'UNABLE_BUTTON'

export {
	FOCUSED_BUTTON,
	UNFOCUSED_BUTTON,
	HIDE_BUTTON,
	SHOW_BUTTON,
	DISABLE_BUTTON,
	UNABLE_BUTTON
}
