const ADD_TODO = 'ADD_TODO'
const DELETE_TODO = 'DELETE_TODO'
const CHECK_TODO = 'CHECK_TODO'
const HIDE_TODO = 'HIDE_TODO'
const SHOW_TODO = 'SHOW_TODO'
const CHANGE_TODO = 'CHANGE_TODO'
const COMPLETED_ALL_TODO = 'COMPLETED_ALL_TODO'
const UNCOMPLETED_ALL_TODO = 'UNCOMPLETED_ALL_TODO'

export {
	ADD_TODO,
	DELETE_TODO,
	CHECK_TODO,
	HIDE_TODO,
	SHOW_TODO,
	CHANGE_TODO,
	COMPLETED_ALL_TODO,
	UNCOMPLETED_ALL_TODO
}
